apiVersion: apps/v1
kind: Deployment
metadata:
  name: preceni-scrape-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preceni-scrape
  template:
    metadata:
      labels:
        app: preceni-scrape
    spec:
      containers:
        - image: vidvidex/preceni-scrape:2023-12-26-12-01-08
          name: preceni-scrape
          env:
          - name: REQUESTS_DELAY
            valueFrom:
              secretKeyRef:
                name: request-delay
                key: req-delay
          - name: DODAJ_IZDELEK_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: addproduct-endpoint
                key: addprod-endpoint

          - name: SCRAPE_SERVICE_PORT
            valueFrom:
              secretKeyRef:
                name: scrape-port
                key: scrape-service-port

          - name: SCRAPE_SERVICE_DEBUG
            valueFrom:
              secretKeyRef:
                name: scrape-debug
                key: scrape-service-debug

          - name: PYTHONUNBUFFERED
            value: "TRUE"

          ports:
            - containerPort: 5004
              name: preceni-scrape

          livenessProbe:
            httpGet:
              path: /scrape/health/live
              port: preceni-scrape
            failureThreshold: 2
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /scrape/health/live
              port: preceni-scrape
            failureThreshold: 2
            initialDelaySeconds: 20
            periodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: preceni-scrape-lb
spec:
  type: LoadBalancer
  ports:
    - port: 5004
      targetPort: 5004
      protocol: TCP
  selector:
    app: preceni-scrape
